Add some Chinese Translation
wh201906/Proxmark3GUI pull request #10
Opened 2020-10-25 05:07 UTC by ruling

Add some Chinese Translation

2020-10-25 05:08 UTC, ruling commented
Add some Chinese Translation

2020-10-26 13:57 UTC, wh201906 requested changes
Thanks for your commit!
Maybe the number should be put after the text?
非常感谢
但我感觉数字是不是放在字后面会好一些？比如“块0”“块1”“密钥A”“数据块访问权限”这种
因为“0块”“1块”这种表达上有点歧义，听着像表达块的数量而不是序号

2020-10-27 03:03 UTC, ruling commented
确实是“块0”“块1”“密钥A”更好一些

2020-10-27 03:04 UTC, closed without merging

2020-10-27 03:07 UTC, wh201906 commented
You can change these texts and make a commit again.
And I will accept your pull request
要不我重新开放这个pr，你可以把这些地方改过来之后再提交一次commit，然后我把你的pr合进去？

2020-10-28 16:02 UTC, ruling commented
好的，你直接说中文吧，要不然你还得翻译成英文😬

wh201906 <notifications@github.com> 于 2020年10月27日周二 上午11:08写道：

> You can change these texts and make a commit again.
> And I will accept your pull request
> 要不我重新开放这个pr，你可以把这些地方改过来之后再提交一次commit，然后我把你的pr合进去？
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/wh201906/Proxmark3GUI/pull/10#issuecomment-716949108>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAYZW7WPLGQC7XYXUXYNURDSMY2RDANCNFSM4S6COWNQ>
> .
>